# Generated by Django 5.2.6 on 2025-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Comfort Food', 'Comfort Food'), ('Quick and Easy', 'Quick and Easy'), ('Low Carb', 'Low Carb'), ('Salads', 'Salads'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='Recipe Image'),
        ),
    ]
